# Builds a .NET framework project
name: Nightly builds

env:
  # Project details
  projectName: FunkeySelectorGUI
  projectFolder: FunkeySelectorGUI
  solutionFile: FunkeySelectorGUI.sln

  # Repo details
  githubRepository: OpenFunk-mirror/FunkeySelectorGUI
  codebergRepository: OpenFunk/FunkeySelectorGUI
  codebergReleaseName: Latest nightly build
  mainBranchName: fix-ci

on:
  workflow_dispatch:

  push:
    branches-ignore:
      - "gh-pages"

  pull_request:
    branches-ignore:
      - "gh-pages"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        configuration: [ Release, Debug ]
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v4

      - name: Setup forgejo cli
        run: |
          curl -O https://codeberg.org/forgejo-contrib/forgejo-cli/releases/download/v0.6.0/forgejo-cli-x86_64-windows.zip
          unzip forgejo-cli-x86_64-windows.zip
          echo "${{ secrets.CODEBERG_TOKEN }}" | ./fj -H codeberg.org auth add-token

      - name: Restore Packages
        run: nuget restore ${{ env.solutionFile }}

      - name: Install .NET Framework v4.0 reference assemblies
        run: |
          nuget install Microsoft.NETFramework.ReferenceAssemblies -Version 1.0.3
          nuget install Microsoft.NETFramework.ReferenceAssemblies.net40 -Version 1.0.3

          $net40path = "C:\Users\runneradmin\.nuget\packages\microsoft.netframework.referenceassemblies.net40\1.0.3\build\.NETFramework\v4.0"
          $net40dest = "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0"
          Copy-Item "$net40path\*" -Destination "$net40dest" -Recurse -Force

      - name: Get version from update.xml
        id: getVersion
        uses: mavrosxristoforos/get-xml-info@2.1.0
        with:
          xml-file: update.xml
          xpath: //update/@version

      - name: Normalize the version string into SemVer format (x.x.x)
        id: normalizeVersion
        run: |
          $versionString = "${{ steps.getVersion.outputs.info }}"
          $digits = $versionString.Split(".").Length
          if ($digits -eq 1) { $versionString += ".0.0" }
          elseif ($digits -eq 2) { $versionString += ".0" }
          "VERSION=$($versionString)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Set version in AssemblyInfo.cs
        uses: secondbounce/assemblyinfo-update@v2
        with:
          version: "${{ steps.normalizeVersion.outputs.VERSION }}"

      - name: Build solution
        run: msbuild ${{ env.solutionFile }} -t:"${{ matrix.configuration == 'Release' && 'clean;' || '' }}rebuild" -property:Configuration=${{ matrix.configuration }}

      - name: Upload the build results as an artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.projectFolder }}/bin/${{ matrix.configuration }}/*
          name: ${{ env.projectName }}.Nightly.${{ matrix.configuration }}

      # We don't upload the .exe.config in Release builds because we consider those clean builds which should have as little clutter as possible
      - name: Copy the build result for easier access
        if: matrix.configuration == 'Release'
        run: mv "${{ env.projectFolder }}/bin/${{ matrix.configuration }}/${{ env.projectFolder }}.exe ."

      - name: Put the build artifacts into an archive file
        if: matrix.configuration == 'Debug'
        # xz compresses better here
        run: |
          cd "${{ env.projectFolder }}/bin/${{ matrix.configuration }}"
          tar -cJf FunkeySelectorGUI.Debug.tar.xz *

      - name: Upload the build results to the nightly builds prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $result = "${{ env.projectName }}.${{ matrix.configuration == 'Release' && 'exe' || 'Debug.tar.xz' }}"
          # assumes there already is an asset with the same name
          gh release delete-asset nightly $result --yes
          gh release upload nightly $result --repo ${{ env.githubRepository }}
          ./fj release asset delete "${{ env.codebergReleaseName }}" $result -H codeberg.org -r ${{ env.codebergRepository }}
          ./fj release asset create "${{ env.codebergReleaseName }}" $result -H codeberg.org -r ${{ env.codebergRepository }}


  finish:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-slim
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup forgejo cli
        shell: bash
        run: |
          curl -O https://codeberg.org/forgejo-contrib/forgejo-cli/releases/download/latest/forgejo-cli-x86_64-linux.tar.gz
          tar -xf forgejo-cli-x86_64-linux.tar.gz
          chmod +x fj
          cp fj /usr/local/bin
          echo "${{ secrets.CODEBERG_TOKEN }}" | fj -H codeberg.org auth add-token

      - name: Set a bunch of variables
        id: info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $filesizes = gh release view --repo ${{ env.githubRepository }} nightly --json assets --jq '[ .assets[] | {name:.name, size:.size} | select(.name | startswith("${{ env.projectName }}")) | {(.name):.size} | to_entries ] | flatten | from_entries' | ConvertFrom-Json
          echo $filesizes
          "FILESIZE_RELEASE=$($filesizes.'${{ env.projectName }}.exe')" >> $env:GITHUB_OUTPUT
          "FILESIZE_DEBUG=$($filesizes.'${{ env.projectName }}.Debug.tar.xz')" >> $env:GITHUB_OUTPUT

          "COMMIT_HASH=$(git log -1 --pretty=format:"%H")" >> $env:GITHUB_OUTPUT
          "SHORT_COMMIT_HASH=$(git log -1 --pretty=format:"%h")" >> $env:GITHUB_OUTPUT
          "LAST_COMMIT_TIMESTAMP=$(Get-Date -Date "$(git log -1 --pretty=format:'%aD')" -Format 'ddd, d MMM yyyy HH:mm:ss zzz')" >> $env:GITHUB_OUTPUT
          "BUILD_TIMESTAMP=$(Get-Date -Format "ddd, d MMM yyyy HH:mm:ss zzz")" >> $env:GITHUB_OUTPUT

      - name: Update update.xml and buld notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $content = @'
          <?xml version="1.0" encoding="utf-8"?>
          <update schema_version="2.0" id="funkeyselectorgui" name="FunkeySelectorGUI" version="${{ steps.info.outputs.COMMIT_HASH }}" version_name="FunkeySelectorGUI@${{ steps.info.outputs.SHORT_COMMIT_HASH }}">
              <variant size="${{ steps.info.outputs.FILESIZE_RELEASE }}" link="https://github.com/${{ env.githubRepository }}/releases/download/nightly/${{ env.projectName }}.exe">
                  <Property key="BuildConfiguration" value="Release" />
              </variant>
              <variant size="${{ steps.info.outputs.FILESIZE_DEBUG }}" link="https://github.com/${{ env.githubRepository }}/releases/download/nightly/${{ env.projectName }}.Debug.tar.xz">
                  <Property key="BuildConfiguration" value="Debug" />
              </variant>
          </update>
          '@
          Set-Content -Path update.xml -Value $content -Encoding utf8
          # assumes there already is an update.xml
          gh release delete-asset nightly update.xml --yes
          gh release upload nightly update.xml --repo ${{ env.githubRepository }}

          $content = $content.Replace("github.com/${{ env.githubRepository }}", "codeberg.org/${{ env.codebergRepository }}")
          Set-Content -Path update.xml -Value $content -Encoding utf8
          # assumes there already is an update.xml
          fj release asset delete "${{ env.codebergReleaseName }}" update.xml -H codeberg.org -r ${{ env.codebergRepository }}
          fj release asset create "${{ env.codebergReleaseName }}" update.xml -H codeberg.org -r ${{ env.codebergRepository }}

          $releaseNotes = @'
          Check the attached files for the latest nightly build.
          Note that the source code download and the tag are NOT kept up to date!

          Current build name: `${{ env.projectName }}@${{ steps.info.outputs.SHORT_COMMIT_HASH }}`
          Current version: `${{ steps.info.outputs.COMMIT_HASH }}`
          Last updated: `${{ steps.info.outputs.LAST_COMMIT_TIMESTAMP }}`
          Built at: `${{ steps.info.outputs.BUILD_TIMESTAMP }}`

          # Which file do I download?
          TLDR: `FunkeySelectorGUI.exe`.

          There are two files available for download: the regular version (FunkeySelectorGUI.exe) and the Debug version (FunkeySelectorGUI.Debug.tar.xz).
          Unless you're planning to use a debugger program, you can disregard the Debug version. It's a pretty obscure usecase anyway, but I aim to serve all of em :)
          '@
          $releaseNotes | gh release edit nightly --notes-file -
          fj release edit -H codeberg.org -r ${{ env.codebergRepository }} -t nightly "${{ env.codebergReleaseName }}" -b $releaseNotes
