# Builds a .NET framework project
name: Nightly builds

env:
  projectName: FunkeySelectorGUI
  projectFolder: FunkeySelector
  solutionFile: FunkeySelector.sln

on:
  workflow_dispatch:
  
  push:
    branches-ignore:
      - "gh-pages"
  
  pull_request:
    branches-ignore:
      - "gh-pages"

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Debug, Release ]
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v3

      - name: Restore Packages
        run: nuget restore ${{ env.solutionFile }}

      - name: Install .NET Framework v4.0 SDK
        run: |
          nuget install Microsoft.NETFramework.ReferenceAssemblies -Version 1.0.3
          nuget install Microsoft.NETFramework.ReferenceAssemblies.net40 -Version 1.0.3

      - run: tree "C:\Users\runneradmin\.nuget\packages\microsoft.netframework.referenceassemblies.net40"
      - run: tree "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework"
      - run: |
          $net40path = "C:\Users\runneradmin\.nuget\packages\microsoft.netframework.referenceassemblies.net40\1.0.3\build\.NETFramework\v4.0"
          $net40dest = "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0"
          Copy-Item "$net40path\*" -Destination "$net40dest" -Recurse
      
      - name: Get version from update.xml
        id: getVersion
        uses: mavrosxristoforos/get-xml-info@2.0
        with:
          xml-file: update.xml
          xpath: //update/@version
      
      - name: Normalize the version string into SemVer format (x.x.x)
        id: normalizeVersion
        run: |
          $versionString = "${{ steps.getVersion.outputs.info }}"
          $digits = $versionString.Split(".").Length
          if ($digits -eq 1) { $versionString += ".0.0" }
          elseif ($digits -eq 2) { $versionString += ".0" }
          "VERSION=$($versionString)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      
      - name: Set version in AssemblyInfo.cs
        uses: secondbounce/assemblyinfo-update@v2
        with:
          version: "${{ steps.normalizeVersion.outputs.VERSION }}"
      
      - name: Build solution
        run: msbuild ${{ env.solutionFile }} -t:rebuild -property:Configuration=${{ matrix.configuration }}
      
      - name: Upload the build results as an artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.projectFolder }}/bin/${{ matrix.configuration }}/*
          name: ${{ env.projectName }}.Nightly.${{ matrix.configuration }}
