# Builds a .NET framework project
name: Nightly builds

env:
  projectName: FunkeySelectorGUI
  projectFolder: FunkeySelectorGUI
  solutionFile: FunkeySelectorGUI.sln

on:
  workflow_dispatch:
  
  push:
    branches-ignore:
      - "gh-pages"
  
  pull_request:
    branches-ignore:
      - "gh-pages"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        configuration: [ Release, Debug ]
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v3

      - name: Restore Packages
        run: nuget restore ${{ env.solutionFile }}

      - name: Install .NET Framework v4.0 reference assemblies
        run: |
          nuget install Microsoft.NETFramework.ReferenceAssemblies -Version 1.0.3
          nuget install Microsoft.NETFramework.ReferenceAssemblies.net40 -Version 1.0.3

          $net40path = "C:\Users\runneradmin\.nuget\packages\microsoft.netframework.referenceassemblies.net40\1.0.3\build\.NETFramework\v4.0"
          $net40dest = "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0"
          Copy-Item "$net40path\*" -Destination "$net40dest" -Recurse -Force
      
      - name: Get version from update.xml
        id: getVersion
        uses: mavrosxristoforos/get-xml-info@2.1.0
        with:
          xml-file: update.xml
          xpath: //update/@version
      
      - name: Normalize the version string into SemVer format (x.x.x)
        id: normalizeVersion
        run: |
          $versionString = "${{ steps.getVersion.outputs.info }}"
          $digits = $versionString.Split(".").Length
          if ($digits -eq 1) { $versionString += ".0.0" }
          elseif ($digits -eq 2) { $versionString += ".0" }
          "VERSION=$($versionString)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      
      - name: Set version in AssemblyInfo.cs
        uses: secondbounce/assemblyinfo-update@v2
        with:
          version: "${{ steps.normalizeVersion.outputs.VERSION }}"
      
      - name: Build solution
        run: msbuild ${{ env.solutionFile }} -t:${{ matrix.configuration == 'Release' && 'clean;' || '' }}rebuild -property:Configuration=${{ matrix.configuration }}
      
      - name: Set a bunch of variables
        id: info
        run: |
          "FILESIZE=$((Get-Item ${{ env.projectFolder }}/bin/${{ matrix.configuration }}/${{ env.projectFolder }}.exe).length)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "COMMIT_HASH=$(git log -1 --pretty=format:"%H")" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "SHORT_COMMIT_HASH=$(git log -1 --pretty=format:"%h")" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          'LAST_COMMIT_TIMESTAMP=$(Get-Date -Date "$(git log -1 --pretty=format:\"%aD\")" -Format "ddd, d MMM yyyy HH:mm:ss zzz")' | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          'BUILD_TIMESTAMP=$(Get-Date -Format "ddd, d MMM yyyy HH:mm:ss zzz")' | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Generate update.xml
        run: echo '<update version="${{ steps.info.outputs.COMMIT_HASH }}" name="${{ env.projectName }}@${{ steps.info.outputs.SHORT_COMMIT_HASH }}" size="${{ steps.info.outputs.FILESIZE }}" url="https://github.com/OpenFunK-mirror/FunkeySelectorGUI/releases/download/nightly/${{ env.projectFolder }}.exe" />' > "${{ env.projectFolder }}/bin/${{ matrix.configuration }}/update.xml"

      - name: Upload the build results as an artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.projectFolder }}/bin/${{ matrix.configuration }}/*
          name: ${{ env.projectName }}.Nightly.${{ matrix.configuration }}

      # We delete this in Release builds because we consider those clean builds which should have as little clutter as possible
      - name: Delete ${{ env.projectFolder }}.exe.config
        if: matrix.configuration == 'Release'
        run: rm "${{ env.projectFolder }}/bin/${{ matrix.configuration }}/${{ env.projectFolder }}.exe.config"

      - name: Put the build artifacts into an archive file
        if: matrix.configuration == 'Debug'
        # xz compresses better here
        run: |
          cd "${{ env.projectFolder }}/bin/${{ matrix.configuration }}"
          tar -cJf FunkeySelectorGUI.tar.xz *

      - name: Upload build results to nightly builds release
        uses: svenstaro/upload-release-action@v2
        if: github.ref_name == 'fix-ci' && github.repository == 'OpenFunk-mirror/FunkeySelectorGUI'
        with:
          tag: nightly
          prerelease: true
          draft: false
          overwrite: true
          file_glob: true
          # Release build job uploads the update.xml and FunkeySelectorGUI.exe files
          # Debug build job uploads FunkeySelectorGUI.Debug.tar.xz
          file: ${{ env.projectFolder }}/bin/${{ matrix.configuration }}/${{ matrix.configuration == 'Release' && '*' || 'FunkeySelectorGUI.Debug.tar.xz' }}
          # This step is ran multiple times in parallel so the body gets overwritten multiple times
          body: |
            Check the attached files for the latest nightly build.
            Note that the source code download and the tag are NOT kept up to date!

            Current build name: `${{ env.projectName }}@${{ steps.info.outputs.SHORT_COMMIT_HASH }}`
            Current version: `${{ steps.info.outputs.COMMIT_HASH }}`
            Last updated: `${{ steps.info.outputs.LAST_COMMIT_DATE }}`
            Built at: `${{ steps.info.outputs.BUILD_DATE }}`

            # Which file do I download?
            There are two files available for download: the regular version (FunkeySelectorGUI.exe) and the Debug version (FunkeySelectorGUI.Debug.tar.xz).
            Unless you're planning to use a debugger program, you can disregard the Debug version. It's a pretty obscure usecase anyway, but I aim to serve all of em :)
